### ISSUE TITLE
build error - Plugin with id 'com.android.library' not found

### ISSUE THREAD

**Issue by Basher7** [AgoraIO/Agora-Flutter-SDK#256]
**flutter run result after error throw**

```dart
[ +137 ms] Building plugin agora_rtc_engine...
[ +276 ms] Running Gradle task 'assembleAarRelease'...
[ +156 ms] gradle.properties already sets `android.enableR8`
[ +130 ms] C:\flutter\bin\cache\artifacts\gradle_wrapper\gradle\wrapper\gradle-wrapper.jar mode: 33206
rw-rw-rw-.
[ +146 ms] C:\flutter\bin\cache\artifacts\gradle_wrapper\gradlew mode: 33206 rw-rw-rw-.
[ +131 ms] C:\flutter\bin\cache\artifacts\gradle_wrapper\gradlew.bat mode: 33279 rwxrwxrwx.
[  +62 ms] C:\\flutter\\.pub-cache\\hosted\\pub.flutter-io.cn\\agora_rtc_engine-3.2.1\\android\gradlew.bat
mode: 33279 rwxrwxrwx.
[ +133 ms] Using gradle from
C:\\flutter\\.pub-cache\\hosted\\pub.flutter-io.cn\\agora_rtc_engine-3.2.1\\android\gradlew.bat.
[ +200 ms] C:\\flutter\\.pub-cache\\hosted\\pub.flutter-io.cn\\agora_rtc_engine-3.2.1\\android\gradlew.bat
mode: 33279 rwxrwxrwx.
[ +289 ms] executing: [C:\\flutter\\.pub-cache\\hosted\\pub.flutter-io.cn\\agora_rtc_engine-3.2.1\\android/]
C:\\flutter\\.pub-cache\\hosted\\pub.flutter-io.cn\\agora_rtc_engine-3.2.1\\android\gradlew.bat
-I=C:\flutter\packages\flutter_tools\gradle\aar_init_script.gradle
-Pflutter-root=C:\flutter -Poutput-dir=<project-root-dir>\build\app
-Pis-plugin=true -PbuildNumber=1.0 -Pverbose=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease
[+3166 ms] 
                    FAILURE: Build failed with an exception.

                    * Where:
                    Build file
                    'C:\flutter\.pub-cache\hosted\pub.flutter-io.cn\agora_rtc_engine-3.2.1\android\build.gradle                    ' line: 28

                    * What went wrong:
                    A problem occurred evaluating root project 'agora_rtc_engine'.
                    > Plugin with id 'com.android.library' not found.

                    * Try:
                    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run                    with --scan to get full insights.

                    * Get more help at https://help.gradle.org

                    BUILD FAILED in 2s
[ +295 ms] Running Gradle task 'assembleAarRelease'... (completed in 4.6s)
[   +6 ms] 
           FAILURE: Build failed with an exception.

           * Where:
           Build file
'C:\flutter\.pub-cache\hosted\pub.flutter-io.cn\agora_rtc_engine-3.2.1\android\build.gradle' line: 28

           * What went wrong:
           A problem occurred evaluating root project 'agora_rtc_engine'.
           > Plugin with id 'com.android.library' not found.

           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with    
--scan to get full insights.

           * Get more help at https://help.gradle.org

           BUILD FAILED in 2s

[+1417 ms] Exception: The plugin agora_rtc_engine could not be built due to the issue above.
[ +105 ms] "flutter run" took 148,125ms.
[  +76 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:607:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


[+2305 ms] ensureAnalyticsSent: 263ms
[   +2 ms] Running shutdown hooks
[   +2 ms] Shutdown hook priority 4
[   +4 ms] Shutdown hooks complete
[ +197 ms] exiting with code 1
```

**Comment by Basher7** [comment]
**Extremely sorry. issue solved after gradle upgrade to gradle-6.5-all.zip from gradle-6.4.1-all.zip**

**Comment by igovind** [comment]
I still have the same issue even after upgrade to 6.5 

> Extremely sorry. issue solved after gradle upgrade to gradle-6.5-all.zip from gradle-6.4.1-all.zip

**Comment by Basher7** [comment]
@igovind you can try this.
upgrade grade version by following
```distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip``` and 
in your ```android\build.gradle``` file set ```classpath 'com.android.tools.build:gradle:4.1.0'```

**Comment by igovind** [comment]
I fixed that issue thank you @Basher7  
Do you know how to make full screen incoming call(accept or reject) instead of simple notification?

**Comment by Basher7** [comment]
@igovind how you fixed that. Please share, may be it can help someone.

**Comment by igovind** [comment]
in my case, simple fix just remove the code from android manifest 
   <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="@string/default_notification_channel_id" />
and it will work fine

**Comment by igovind** [comment]
![Screen Shot 2021-05-30 at 12 11 29](https://user-images.githubusercontent.com/50535437/120094811-2e130c00-c140-11eb-931f-1a23b3dd35c2.png)
 
just comment out this code in your AndroidMenifest.xml  file and it will work fine

**Comment by deeenz** [comment]
this is not in any ways related to the problem
