### ISSUE TITLE
Is that worked with flutter Web?

### ISSUE THREAD

**Issue by amarSuthar437** [AgoraIO/Agora-Flutter-SDK#258]
**Is that worked with flutter Web?**

When i have implement with web, i getting this issue.

Error: PlatformException(Unimplemented, null, agora_rtc_engine for web doesn't implement 'create', null)
    at Object.throw_ [as throw] (http://localhost:58781/dart_sdk.js:5342:11)
    at StandardMethodCodec.decodeEnvelope (http://localhost:58781/packages/flutter/src/services/system_channels.dart.lib.js:797:19)
    at MethodChannel._invokeMethod (http://localhost:58781/packages/flutter/src/services/system_channels.dart.lib.js:962:47)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:58781/dart_sdk.js:39157:33
    at _RootZone.runUnary (http://localhost:58781/dart_sdk.js:39014:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:58781/dart_sdk.js:34000:29)
    at handleValueCallback (http://localhost:58781/dart_sdk.js:34560:49)
    at Function._propagateToListeners (http://localhost:58781/dart_sdk.js:34598:17)
    at _Future.new.[_completeWithValue] (http://localhost:58781/dart_sdk.js:34440:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:58781/dart_sdk.js:34463:35)
    at Object._microtaskLoop (http://localhost:58781/dart_sdk.js:39301:13)
    at _startMicrotaskLoop (http://localhost:58781/dart_sdk.js:39307:13)
    at http://localhost:58781/dart_sdk.js:34814:9

**Comment by yoreland** [comment]
duplicated with https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/issues/214
let's track this item there..
