### ISSUE TITLE
agor_rtc_engine 3.3.3 gives error when run

### ISSUE THREAD

**Issue by ziasultan2** [AgoraIO/Agora-Flutter-SDK#298]
**Describe the bug**
In agora_rtc_engine: 3.3.3 gives me error when run

**To Reproduce**
flutter run -d 83

** Error output **
```
Zia-Sultan:yurr-app-features-celebrity-order Raymond$ flutter run -d 83
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
 
Running pod install...                                              1.9s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
      Using `ARCHS` setting to build architectures of target
      `Pods-OneSignalNotificationServiceExtension`: (``)

    Finding Podfile changes
      - Flutter
      - OneSignal
      - agora_rtc_engine
      - flutter_ios_voip_kit
      - image_picker
      - onesignal_flutter
      - path_provider
      - permission_handler
      - shared_preferences
      - video_player

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `agora_rtc_engine` from
    `.symlinks/plugins/agora_rtc_engine/ios`
    -> Fetching podspec for `flutter_ios_voip_kit` from
    `.symlinks/plugins/flutter_ios_voip_kit/ios`
    -> Fetching podspec for `image_picker` from
    `.symlinks/plugins/image_picker/ios`
    -> Fetching podspec for `onesignal_flutter` from
    `.symlinks/plugins/onesignal_flutter/ios`
    -> Fetching podspec for `path_provider` from
    `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `permission_handler` from
    `.symlinks/plugins/permission_handler/ios`
    -> Fetching podspec for `shared_preferences` from
    `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `video_player` from
    `.symlinks/plugins/video_player/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_c_1_2.txt exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/1/2/OneSignal/3.4.1/OneSignal.podspec.json
      exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_1_d_9.txt exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path:
      Specs/1/d/9/AgoraRtcEngine_iOS/3.3.2/AgoraRtcEngine_iOS.podspec.json exists!
      Returning local because checking is only perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "AgoraRtcEngine_iOS":
      In snapshot (Podfile.lock):
        AgoraRtcEngine_iOS (= 3.2.1)

      In Podfile:
        agora_rtc_engine (from `.symlinks/plugins/agora_rtc_engine/ios`) was
        resolved to 3.3.3, which depends on
          AgoraRtcEngine_iOS (= 3.3.2)


    You have either:
     * out-of-date source repos which you can update with `pod repo update` or
     with `pod install --repo-update`.
     * changed the constraints of dependency `AgoraRtcEngine_iOS` inside your
     development pod `agora_rtc_engine`.
       You should run `pod update AgoraRtcEngine_iOS` to apply changes you've
       made.

    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:
    in `raise_error_unless_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:
    in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:
    in `tap'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:
    in `unwind_for_conflict'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:257:
    in `process_topmost_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:
    in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in
    `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:94:in
    `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer
    .rb:986:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:
    64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer
    .rb:984:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer
    .rb:124:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:i
    n `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:i
    n `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:
    64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:i
    n `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:i
    n `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb
    :52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in
    `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update



Error running pod install
Error launching application on iPhone 11 Pro Max.
Zia-Sultan:yurr-app-features-celebrity-order Raymond$ 
```

**Flutter doctor **
```
Zia-Sultan:yurr-app-features-celebrity-order Raymond$ flutter doctor -v
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.20.2 at /Users/johnsmith/Developer/flutter
    • Framework revision bbfbf1770c (8 months ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/Raymond Tucker/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • 8382A243-0357-4EAB-AE4E-6983C02AB556 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
```

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
iOS 13
iPhone simulator 11 pro max

**Comment by LichKing-2234** [comment]
you should run `pod update` on our iOS folder

**Comment by ziasultan2** [comment]
I did this  but still showing me error
```
Zia-Sultan:ios Raymond$ pod update
Update all pods
Updating local specs repositories

CocoaPods 1.10.1 is available.
To update use: `sudo gem install cocoapods`

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.10.1

Analyzing dependencies
Downloading dependencies
Installing AgoraRtcEngine_iOS (3.3.2)
Installing Flutter (1.0.0)
Installing OneSignal (2.16.1)
Installing agora_rtc_engine (3.3.3)
Installing flutter_ios_voip_kit (0.0.1)
Installing image_picker (0.0.1)
Installing onesignal_flutter (2.6.2)
Installing path_provider (0.0.1)
Installing permission_handler (5.0.0)
Installing shared_preferences (0.0.1)
Installing video_player (0.0.1)
[!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/Raymond Tucker/AndroidStudioProjects/yurr/yurr-app-features-celebrity-order/ios/Pods/AgoraRtcEngine_iOS/AgoraAIDenoiseExtension.xcframework, /Users/Raymond Tucker/AndroidStudioProjects/yurr/yurr-app-features-celebrity-order/ios/Pods/AgoraRtcEngine_iOS/AgoraRtcKit.xcframework, /Users/Raymond Tucker/AndroidStudioProjects/yurr/yurr-app-features-celebrity-order/ios/Pods/AgoraRtcEngine_iOS/Agoraffmpeg.xcframework, /Users/Raymond Tucker/AndroidStudioProjects/yurr/yurr-app-features-celebrity-order/ios/Pods/AgoraRtcEngine_iOS/AgoraCore.xcframework, /Users/Raymond Tucker/AndroidStudioProjects/yurr/yurr-app-features-celebrity-order/ios/Pods/AgoraRtcEngine_iOS/AgoraSoundTouch.xcframework, /Users/Raymond Tucker/AndroidStudioProjects/yurr/yurr-app-features-celebrity-order/ios/Pods/AgoraRtcEngine_iOS/Agorafdkaac.xcframework, and /Users/Raymond Tucker/AndroidStudioProjects/yurr/yurr-app-features-celebrity-order/ios/Pods/AgoraRtcEngine_iOS/AgoraDav1dExtension.xcframework)
Zia-Sultan:ios Raymond$ cd ../
Zia-Sultan:yurr-app-features-celebrity-order Raymond$ flutter run -d 83
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
 
Running pod install...                                              2.4s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
      Using `ARCHS` setting to build architectures of target
      `Pods-OneSignalNotificationServiceExtension`: (``)

    Finding Podfile changes
      - Flutter
      - OneSignal
      - agora_rtc_engine
      - flutter_ios_voip_kit
      - image_picker
      - onesignal_flutter
      - path_provider
      - permission_handler
      - shared_preferences
      - video_player

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `agora_rtc_engine` from
    `.symlinks/plugins/agora_rtc_engine/ios`
    -> Fetching podspec for `flutter_ios_voip_kit` from
    `.symlinks/plugins/flutter_ios_voip_kit/ios`
    -> Fetching podspec for `image_picker` from
    `.symlinks/plugins/image_picker/ios`
    -> Fetching podspec for `onesignal_flutter` from
    `.symlinks/plugins/onesignal_flutter/ios`
    -> Fetching podspec for `path_provider` from
    `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `permission_handler` from
    `.symlinks/plugins/permission_handler/ios`
    -> Fetching podspec for `shared_preferences` from
    `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `video_player` from
    `.symlinks/plugins/video_player/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_c_1_2.txt exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/1/2/OneSignal/3.4.1/OneSignal.podspec.json
      exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_1_d_9.txt exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path:
      Specs/1/d/9/AgoraRtcEngine_iOS/3.3.2/AgoraRtcEngine_iOS.podspec.json exists!
      Returning local because checking is only perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "AgoraRtcEngine_iOS":
      In snapshot (Podfile.lock):
        AgoraRtcEngine_iOS (= 3.2.1)

      In Podfile:
        agora_rtc_engine (from `.symlinks/plugins/agora_rtc_engine/ios`) was
        resolved to 3.3.3, which depends on
          AgoraRtcEngine_iOS (= 3.3.2)


    You have either:
     * out-of-date source repos which you can update with `pod repo update` or
     with `pod install --repo-update`.
     * changed the constraints of dependency `AgoraRtcEngine_iOS` inside your
     development pod `agora_rtc_engine`.
       You should run `pod update AgoraRtcEngine_iOS` to apply changes you've
       made.

    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:
    in `raise_error_unless_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:
    in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:
    in `tap'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:
    in `unwind_for_conflict'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:257:
    in `process_topmost_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:
    in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in
    `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:94:in
    `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer
    .rb:986:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:
    64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer
    .rb:984:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer
    .rb:124:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:i
    n `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:i
    n `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:
    64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:i
    n `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:i
    n `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb
    :52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in
    `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update



Error running pod install
Error launching application on iPhone 11 Pro Max.

```
pod repo update
````
Zia-Sultan:yurr-app-features-celebrity-order Raymond$ cd ios/
Zia-Sultan:ios Raymond$ pod repo update
Updating spec repo `trunk`

CocoaPods 1.10.1 is available.
To update use: `sudo gem install cocoapods`

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.10.1

Zia-Sultan:ios Raymond$ cd ../
Zia-Sultan:yurr-app-features-celebrity-order Raymond$ flutter run -d 83
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
 
Running pod install...                                              2.1s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
      Using `ARCHS` setting to build architectures of target
      `Pods-OneSignalNotificationServiceExtension`: (``)

    Finding Podfile changes
      - Flutter
      - OneSignal
      - agora_rtc_engine
      - flutter_ios_voip_kit
      - image_picker
      - onesignal_flutter
      - path_provider
      - permission_handler
      - shared_preferences
      - video_player

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `agora_rtc_engine` from
    `.symlinks/plugins/agora_rtc_engine/ios`
    -> Fetching podspec for `flutter_ios_voip_kit` from
    `.symlinks/plugins/flutter_ios_voip_kit/ios`
    -> Fetching podspec for `image_picker` from
    `.symlinks/plugins/image_picker/ios`
    -> Fetching podspec for `onesignal_flutter` from
    `.symlinks/plugins/onesignal_flutter/ios`
    -> Fetching podspec for `path_provider` from
    `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `permission_handler` from
    `.symlinks/plugins/permission_handler/ios`
    -> Fetching podspec for `shared_preferences` from
    `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `video_player` from
    `.symlinks/plugins/video_player/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_c_1_2.txt exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/1/2/OneSignal/3.4.1/OneSignal.podspec.json
      exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_1_d_9.txt exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path:
      Specs/1/d/9/AgoraRtcEngine_iOS/3.3.2/AgoraRtcEngine_iOS.podspec.json exists!
      Returning local because checking is only perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "AgoraRtcEngine_iOS":
      In snapshot (Podfile.lock):
        AgoraRtcEngine_iOS (= 3.2.1)

      In Podfile:
        agora_rtc_engine (from `.symlinks/plugins/agora_rtc_engine/ios`) was
        resolved to 3.3.3, which depends on
          AgoraRtcEngine_iOS (= 3.3.2)


    You have either:
     * out-of-date source repos which you can update with `pod repo update` or
     with `pod install --repo-update`.
     * changed the constraints of dependency `AgoraRtcEngine_iOS` inside your
     development pod `agora_rtc_engine`.
       You should run `pod update AgoraRtcEngine_iOS` to apply changes you've
       made.

    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:
    in `raise_error_unless_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:
    in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:
    in `tap'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:
    in `unwind_for_conflict'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:257:
    in `process_topmost_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:
    in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in
    `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:94:in
    `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer
    .rb:986:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:
    64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer
    .rb:984:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer
    .rb:124:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:i
    n `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:i
    n `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:
    64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:i
    n `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:i
    n `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb
    :52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in
    `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update



Error running pod install
Error launching application on iPhone 11 Pro Max.
Zia-Sultan:yurr-app-features-celebrity-order Raymond$ 
```

**Comment by ziasultan2** [comment]
my pod repo update or pod update gives me this warning
```
[!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/Raymond Tucker/AndroidStudioProjects/yurr/yurr-app-features-celebrity-order/ios/Pods/AgoraRtcEngine_iOS/AgoraAIDenoiseExtension.xcframework, /Users/Raymond Tucker/AndroidStudioProjects/yurr/yurr-app-features-celebrity-order/ios/Pods/AgoraRtcEngine_iOS/AgoraRtcKit.xcframework, /Users/Raymond Tucker/AndroidStudioProjects/yurr/yurr-app-features-celebrity-order/ios/Pods/AgoraRtcEngine_iOS/Agoraffmpeg.xcframework, /Users/Raymond Tucker/AndroidStudioProjects/yurr/yurr-app-features-celebrity-order/ios/Pods/AgoraRtcEngine_iOS/AgoraCore.xcframework, /Users/Raymond Tucker/AndroidStudioProjects/yurr/yurr-app-features-celebrity-order/ios/Pods/AgoraRtcEngine_iOS/AgoraSoundTouch.xcframework, /Users/Raymond Tucker/AndroidStudioProjects/yurr/yurr-app-features-celebrity-order/ios/Pods/AgoraRtcEngine_iOS/Agorafdkaac.xcframework, and /Users/Raymond Tucker/AndroidStudioProjects/yurr/yurr-app-features-celebrity-order/ios/Pods/AgoraRtcEngine_iOS/AgoraDav1dExtension.xcframework)
```

**Comment by LichKing-2234** [comment]
pls make sure your cocoapods is latest version
