### ISSUE TITLE
agor_rtc_engine 3.3.3 gives error when run

### ISSUE THREAD

**Issue by ziasultan2** [AgoraIO/Agora-Flutter-SDK#299]
**Describe the bug**
Pod update pod repo update nothing works

This is the pod update or pod repo update output
```
The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/Raymond Tucker/AndroidStudioProjects/yurr/yurr-app-features-celebrity-order/ios/Pods/AgoraRtcEngine_iOS/AgoraAIDenoiseExtension.xcframework, /Users/Raymond Tucker/AndroidStudioProjects/yurr/yurr-app-features-celebrity-order/ios/Pods/AgoraRtcEngine_iOS/AgoraRtcKit.xcframework, /Users/Raymond Tucker/AndroidStudioProjects/yurr/yurr-app-features-celebrity-order/ios/Pods/AgoraRtcEngine_iOS/Agoraffmpeg.xcframework, /Users/Raymond Tucker/AndroidStudioProjects/yurr/yurr-app-features-celebrity-order/ios/Pods/AgoraRtcEngine_iOS/AgoraCore.xcframework, /Users/Raymond Tucker/AndroidStudioProjects/yurr/yurr-app-features-celebrity-order/ios/Pods/AgoraRtcEngine_iOS/AgoraSoundTouch.xcframework, /Users/Raymond Tucker/AndroidStudioProjects/yurr/yurr-app-features-celebrity-order/ios/Pods/AgoraRtcEngine_iOS/Agorafdkaac.xcframework, and /Users/Raymond Tucker/AndroidStudioProjects/yurr/yurr-app-features-celebrity-order/ios/Pods/AgoraRtcEngine_iOS/AgoraDav1dExtension.xcframework)
```
Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update

This is the final output when run after update
```
Zia-Sultan:yurr-app-features-celebrity-order Raymond$ flutter run -d 83Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
 
Running pod install...                                              1.8s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
      Using `ARCHS` setting to build architectures of target
      `Pods-OneSignalNotificationServiceExtension`: (``)

    Finding Podfile changes
      - Flutter
      - OneSignal
      - agora_rtc_engine
      - flutter_ios_voip_kit
      - image_picker
      - onesignal_flutter
      - path_provider
      - permission_handler
      - shared_preferences
      - video_player

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `agora_rtc_engine` from
    `.symlinks/plugins/agora_rtc_engine/ios`
    -> Fetching podspec for `flutter_ios_voip_kit` from
    `.symlinks/plugins/flutter_ios_voip_kit/ios`
    -> Fetching podspec for `image_picker` from
    `.symlinks/plugins/image_picker/ios`
    -> Fetching podspec for `onesignal_flutter` from
    `.symlinks/plugins/onesignal_flutter/ios`
    -> Fetching podspec for `path_provider` from
    `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `permission_handler` from
    `.symlinks/plugins/permission_handler/ios`
    -> Fetching podspec for `shared_preferences` from
    `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `video_player` from
    `.symlinks/plugins/video_player/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local
      because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_c_1_2.txt exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/1/2/OneSignal/3.4.1/OneSignal.podspec.json
      exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_1_d_9.txt exists! Returning
      local because checking is only perfomed in repo update
      CDN: trunk Relative path:
      Specs/1/d/9/AgoraRtcEngine_iOS/3.3.2/AgoraRtcEngine_iOS.podspec.json exists!
      Returning local because checking is only perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "AgoraRtcEngine_iOS":
      In snapshot (Podfile.lock):
        AgoraRtcEngine_iOS (= 3.2.1)

      In Podfile:
        agora_rtc_engine (from `.symlinks/plugins/agora_rtc_engine/ios`) was
        resolved to 3.3.3, which depends on
          AgoraRtcEngine_iOS (= 3.3.2)


    You have either:
     * out-of-date source repos which you can update with `pod repo update` or
     with `pod install --repo-update`.
     * changed the constraints of dependency `AgoraRtcEngine_iOS` inside your
     development pod `agora_rtc_engine`.
       You should run `pod update AgoraRtcEngine_iOS` to apply changes you've
       made.

    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:
    in `raise_error_unless_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:
    in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:
    in `tap'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:
    in `unwind_for_conflict'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:257:
    in `process_topmost_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:
    in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in
    `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:94:in
    `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer
    .rb:986:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:
    64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer
    .rb:984:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer
    .rb:124:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:i
    n `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:i
    n `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:
    64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:i
    n `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:i
    n `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb
    :52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in
    `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update
```

**Comment by LichKing-2234** [comment]
pls make sure your cocoapods is latest version

and run pod update on your ios folder

**Comment by ziasultan2** [comment]
I update that but shows same error doesn't work. 
So, I try 3.2.1

But Here I face the issue createWithConfig is not found.
 widget._engine = await RtcEngine.createWithConfig(RtcEngineConfig(appId));

Can you please tell me what can I do for substitues of this

**Comment by LichKing-2234** [comment]
pls provide flutter doctor -v
