### ISSUE TITLE
Agora SDK somehow conflicts with firestore so that doesn't work anymore

### ISSUE THREAD

**Issue by sils** [AgoraIO/Agora-Flutter-SDK#359]
**Describe the bug**

On a fresh project with firestore and agora, firestore will seize to work (go to offline mode) when the agora plugin is installed (not even used). This behaviour only happens on android and only on a release build, never on debug or iOS.

**To Reproduce**

Minimal code and reproduction instructions at https://gist.github.com/sils/fc3aba6242d5a7a9091b3cd766b3db7b
Just follow those and set up a fresh project with a firebase db according to the specs written there.

```
flutter clean
flutter pub get
flutter build apk --release
flutter run --release
# Actual: Shows 'null'
# Expected: Shows 'test'
# Press q to exit session
# There are no debug logs shown

flutter pub remove agora_rtc_engine
flutter clean
flutter pub get
flutter build apk --release
# Uninstall the APK from the phone now!
flutter run --release
# Shows 'test' correctly loaded from the firebase database


# Bonus: it works on debug mode! The bug only happens on release.
flutter pub add agora_rtc_engine
flutter clean
flutter pub get
flutter build apk --debug
flutter run --debug
# Shows 'test', even with agora and firebase combined
```

**Expected behavior**
'test' is shown

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4a, also reproduced on some old honor phone lying around
 - OS: Android 11
 - Browser: Brave
 - Version: 1.26.71, Chromium 91

**Additional context**
Just look at the [gist](https://gist.github.com/sils/fc3aba6242d5a7a9091b3cd766b3db7b), I made a full minimal reproduction for you.

**Comment by sils** [comment]
I'd love to use agora FWIW, the app is complete but if there's no quick solution I'm going to have to rip it out and replace it cause I''m a bit on a timeline :(

**Comment by LichKing-2234** [comment]
just dependency our SDK, not calling any API?

**Comment by sils** [comment]
Correct, as mentioned in the minimal example shell script, just the `flutter pub add agora_rtc_engine` makes the issue appear

**Comment by sils** [comment]
Also I can give individuals access to the full project including the firebase config if that helps and/or jump on a debug call.

**Comment by sils** [comment]
Just in case - upgrading to 4.1.0 alpha 2 doesn't solve it in case it matters.

**Comment by LichKing-2234** [comment]
any error log from firestore?

**Comment by sils** [comment]
Nothing that comes up in the usual logs, I did get a bunch of stuff on logcat but it's really hard to sort out what belongs to what and was caused by what. This seems to be related:

```
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: [Channel<1>: (firestore.googleapis.com)] Uncaught exception in the SynchronizationContext. Panic!
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: java.lang.ExceptionInInitializerError
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: 	at d.b.M1.l.m(Unknown Source:22)
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: 	at d.b.L1.I.m(Unknown Source:4)
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: 	at d.b.L1.X1.A(:3)
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: 	at d.b.L1.H1.run(Unknown Source:36)
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: 	at d.b.I1.a(Unknown Source:24)
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: 	at d.b.I1.execute(:2)
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: 	at d.b.L1.L2.b(Unknown Source:9)
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: 	at d.b.L1.W0.a(:10)
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: 	at d.b.L1.W0.run(Unknown Source:38)
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: 	at java.lang.Thread.run(Thread.java:923)
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: d.b.M1.L.t.a.values []
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: 	at java.lang.Enum.enumValues(Enum.java:270)
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: 	at java.lang.Enum.access$000(Enum.java:61)
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: 	at java.lang.Enum$1.create(Enum.java:277)
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: 	at java.lang.Enum$1.create(Enum.java:275)
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: 	at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: 	at java.lang.Enum.getSharedConstants(Enum.java:289)
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: 	at java.lang.Class.getEnumConstantsShared(Class.java:2428)
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: 	at java.util.EnumMap.getKeyUniverse(EnumMap.java:755)
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: 	at java.util.EnumMap.<init>(EnumMap.java:138)
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: 	at d.b.M1.y.<clinit>(:1)
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: 	... 12 more
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: Caused by: java.lang.NoSuchMethodException: d.b.M1.L.t.a.values []
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: 	at java.lang.Class.getMethod(Class.java:2072)
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: 	at java.lang.Class.getDeclaredMethod(Class.java:2050)
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: 	at java.lang.Enum.enumValues(Enum.java:267)
07-01 14:50:47.183 15973 16035 E d.b.L1.Y2: 	... 21 more
07-01 14:50:47.185 15973 16026 W Firestore: (23.0.1) [p0]: (d2baa79) Stream closed with status: C1{code=INTERNAL, description=Panic! This is a bug!, cause=java.lang.ExceptionInInitializerError
07-01 14:50:47.185 15973 16026 W Firestore: 	at d.b.M1.l.m(Unknown Source:22)
07-01 14:50:47.185 15973 16026 W Firestore: 	at d.b.L1.I.m(Unknown Source:4)
07-01 14:50:47.185 15973 16026 W Firestore: 	at d.b.L1.X1.A(:3)
07-01 14:50:47.185 15973 16026 W Firestore: 	at d.b.L1.H1.run(Unknown Source:36)
07-01 14:50:47.185 15973 16026 W Firestore: 	at d.b.I1.a(Unknown Source:24)
07-01 14:50:47.185 15973 16026 W Firestore: 	at d.b.I1.execute(:2)
07-01 14:50:47.185 15973 16026 W Firestore: 	at d.b.L1.L2.b(Unknown Source:9)
07-01 14:50:47.185 15973 16026 W Firestore: 	at d.b.L1.W0.a(:10)
07-01 14:50:47.185 15973 16026 W Firestore: 	at d.b.L1.W0.run(Unknown Source:38)
07-01 14:50:47.185 15973 16026 W Firestore: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-01 14:50:47.185 15973 16026 W Firestore: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-01 14:50:47.185 15973 16026 W Firestore: 	at java.lang.Thread.run(Thread.java:923)
07-01 14:50:47.185 15973 16026 W Firestore: Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: d.b.M1.L.t.a.values []
07-01 14:50:47.185 15973 16026 W Firestore: 	at java.lang.Enum.enumValues(Enum.java:270)
07-01 14:50:47.185 15973 16026 W Firestore: 	at java.lang.Enum.access$000(Enum.java:61)
07-01 14:50:47.185 15973 16026 W Firestore: 	at java.lang.Enum$1.create(Enum.java:277)
07-01 14:50:47.185 15973 16026 W Firestore: 	at java.lang.Enum$1.create(Enum.java:275)
07-01 14:50:47.185 15973 16026 W Firestore: 	at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
07-01 14:50:47.185 15973 16026 W Firestore: 	at java.lang.Enum.getSharedConstants(Enum.java:289)
07-01 14:50:47.185 15973 16026 W Firestore: 	at java.lang.Class.getEnumConstantsShared(Class.java:2428)
07-01 14:50:47.185 15973 16026 W Firestore: 	at java.util.EnumMap.getKeyUniverse(EnumMap.java:755)
07-01 14:50:47.185 15973 16026 W Firestore: 	at java.util.EnumMap.<init>(EnumMap.java:138)
07-01 14:50:47.185 15973 16026 W Firestore: 	at d.b.M1.y.<clinit>(:1)
07-01 14:50:47.185 15973 16026 W Firestore: 	... 12 more
07-01 14:50:47.185 15973 16026 W Firestore: Caused by: java.lang.NoSuchMethodException: d.b.M1.L.t.a.values []
07-01 14:50:47.185 15973 16026 W Firestore: 	at java.lang.Class.getMethod(Class.java:2072)
07-01 14:50:47.185 15973 16026 W Firestore: 	at java.lang.Class.getDeclaredMethod(Class.java:2050)
07-01 14:50:47.185 15973 16026 W Firestore: 	at java.lang.Enum.enumValues(Enum.java:267)
07-01 14:50:47.185 15973 16026 W Firestore: 	... 21 more
07-01 14:50:47.185 15973 16026 W Firestore: }.
07-01 14:50:47.186 15973 16026 W Firestore: (23.0.1) [OnlineStateTracker]: Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: C1{code=INTERNAL, description=Panic! This is a bug!, cause=java.lang.ExceptionInInitializerError
```

Oh and the firebase support just answerred that this seems to be an issue in combination with agora which they don't know so they can't help. :/

**Comment by LichKing-2234** [comment]
is it working on debug mode? seem like an issue caused by ProGuard

**Comment by sils** [comment]
Yes, it works on debug, just not on release.

**Comment by LichKing-2234** [comment]
https://developer.android.com/studio/build/shrink-code?hl=zh-cn#groovy

**Comment by LichKing-2234** [comment]
you can refer to this doc, and set minifyEnabled to false.
https://developer.android.com/studio/build/shrink-code#groovy

if you want to set minifyEnabled to true, make sure you have added the proguard rule of firestore.

**Comment by sils** [comment]
Trying to disable all this now, I remember trying disabling obfuscation and other kinds of things but let me be sure.

**Comment by sils** [comment]
```
    buildTypes {
        release {
            signingConfig signingConfigs.release
            useProguard false
            shrinkResources false
            minifyEnabled false
        }
    }
```

Not to be overly enthusiastic, but if I'm not mistaken it works now. Gonna play further with those options.
