### ISSUE TITLE
Changing video dimension after joining the channel crashes on web (dev/flutter2)

### ISSUE THREAD

**Issue by reeteshranjan** [AgoraIO/Agora-Flutter-SDK#377]
**Describe the bug**
Changing video dimension using `setVideoEncoderConfiguration` API after joining the channel crashes on web version. It works fine on app.

**To Reproduce**
1. Set a video dimension using `setVideoEncoderConfiguration`
2. Join a channel
3. Set another dimension using `setVideoEncoderConfiguration` after the UI is visible (use a button to initiate this)

**Expected behavior**
Setting the video dimension should work on web version as it does on iOS and Android.

**Crash log**
```exception
Uncaught PlatformException(error, TypeError: Cannot read property 'getTrackId' of undefined, null, null)
    at Object.c (https://dev-portal.dhwanilaya.com/main.dart.js:3962:3)
    at aqw.Iq (https://dev-portal.dhwanilaya.com/main.dart.js:76192:14)
    at https://dev-portal.dhwanilaya.com/main.dart.js:76280:98
    at aGM.a (https://dev-portal.dhwanilaya.com/main.dart.js:5625:71)
    at aGM.$2 (https://dev-portal.dhwanilaya.com/main.dart.js:40235:23)
    at aFl.$1 (https://dev-portal.dhwanilaya.com/main.dart.js:40227:30)
    at a0m.n9 (https://dev-portal.dhwanilaya.com/main.dart.js:41369:41)
    at ayf.$0 (https://dev-portal.dhwanilaya.com/main.dart.js:40685:11)
    at Object.zJ (https://dev-portal.dhwanilaya.com/main.dart.js:5747:40)
    at ad.pp (https://dev-portal.dhwanilaya.com/main.dart.js:40602:3)
```

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.4
 - Browser: Chrome, Brave
 - Version: latest

**Comment by LichKing-2234** [comment]
I will take a look next week.

**Comment by LichKing-2234** [comment]
Fixed.
