### ISSUE TITLE
[dev/flutter2] Web doesn't support screen sharing

### ISSUE THREAD

**Issue by vlidholt** [AgoraIO/Agora-Flutter-SDK#414]
**Describe the bug**
Documentation hints that screen sharing is supported for web, but when trying to start screen sharing an exception is thrown.

**To Reproduce**
Run the screen share example. Try to share the screen.

**Expected behavior**
An exception is thrown:

Error: PlatformException(ErrorCode.NotSupported, null, null, null)
    at Object.throw_ [as throw] (http://localhost:57109/dart_sdk.js:5041:11)
    at rtc_engine.RtcEngine.__.startScreenCaptureByWindowId (http://localhost:57109/packages/agora_rtc_engine/src/rtc_engine_extension_web.dart.lib.js:2899:17)
    at video_call._State.new._startScreenShare (http://localhost:57109/packages/buzz_flutter/src/pages/video_call.dart.lib.js:991:22)
    at _startScreenShare.next (<anonymous>)
    at http://localhost:57109/dart_sdk.js:37403:33
    at _RootZone.runUnary (http://localhost:57109/dart_sdk.js:37274:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:57109/dart_sdk.js:32530:29)
    at handleValueCallback (http://localhost:57109/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:57109/dart_sdk.js:33095:17)
    at _Future.new.[_completeWithValue] (http://localhost:57109/dart_sdk.js:32943:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:57109/dart_sdk.js:32964:35)
    at Object._microtaskLoop (http://localhost:57109/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:57109/dart_sdk.js:37532:13)
    at http://localhost:57109/dart_sdk.js:33303:9

**Desktop (please complete the following information):**
Chrome / web

**Comment by vlidholt** [comment]
Got it working.
