### ISSUE TITLE
Agora RTC Engine 4.1.0-alpha.0  Windows not supported

### ISSUE THREAD

**Issue by sujanmt** [AgoraIO/Agora-Flutter-SDK#559]
**Describe the bug**
Not able to run on Windows platform with version 4.1.0-alpha.0

**Expected behavior**
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method create on channel agora_rtc_engine)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      RtcEngine.createWithContext (package:agora_rtc_engine/src/rtc_engine.dart:165:5)
<asynchronous suspension>
#2      _State._initEngine (package:agora_rtc_engine_example/examples/basic/join_channel_video/join_channel_video.dart:39:15)
<asynchronous suspension>

**Comment by ash720** [comment]
I am facing this same issue in Flutter Windows v2.8.0

**Comment by sarinkarma** [comment]
Facing the same issue on windows

**Comment by sabinxmaharjan** [comment]
Stuck on this same issue for weeks now!!

**Comment by poshan0126** [comment]
I am facing the same issue in windows(Flutter version 2.5).

**Comment by KrishnaRauniyar** [comment]
Same issue on windows!!!!!

**Comment by ash720** [comment]
> I am facing this same issue in Flutter Windows v2.8.0

i have tried to change main branch to dev/flutter2 and then I run it...this worked for me!!!.

**Comment by littleGnAl** [comment]
The desktop features are supported now, pls try `agora_rtc_engine: ^5.0.0`

**Comment by bombo774** [comment]
facing this issue on flutter 2.10.4

**Comment by bombo774** [comment]
[2022-04-17 09:33:35.800] [23440] [debug] C:\workspace\workspace\AD\Agora-Iris\IRIS-SDK\rtc\cxx\src\iris_rtc_engine.cc:104 agora::iris::rtc::IrisRtcEngine::CallApi api_type 0 params {"context":{"appId":"XXXXXXX"},"appGroup":null}
[2022-04-17 09:33:35.802] [23440] [debug] C:\workspace\workspace\AD\Agora-Iris\IRIS-SDK\rtc\cxx\src\iris_rtc_engine.cc:114 agora::iris::rtc::IrisRtcEngine::CallApi ret 0 result 
[2022-04-17 09:33:35.803] [23440] [debug] C:\workspace\workspace\AD\Agora-Iris\IRIS-SDK\rtc\cxx\src\iris_rtc_engine.cc:104 agora::iris::rtc::IrisRtcEngine::CallApi api_type 162 params {"appType":4}
[2022-04-17 09:33:35.803] [23440] [debug] C:\workspace\workspace\AD\Agora-Iris\IRIS-SDK\rtc\cxx\src\iris_rtc_engine.cc:114 agora::iris::rtc::IrisRtcEngine::CallApi ret 0 result 
[2022-04-17 09:33:35.808] [23440] [debug] C:\workspace\workspace\AD\Agora-Iris\IRIS-SDK\rtc\cxx\src\iris_rtc_engine.cc:104 agora::iris::rtc::IrisRtcEngine::CallApi api_type 2 params {"profile":1}
[2022-04-17 09:33:35.808] [23440] [debug] C:\workspace\workspace\AD\Agora-Iris\IRIS-SDK\rtc\cxx\src\iris_rtc_engine.cc:114 agora::iris::rtc::IrisRtcEngine::CallApi ret 0 result 
[2022-04-17 09:33:35.821] [23440] [debug] C:\workspace\workspace\AD\Agora-Iris\IRIS-SDK\rtc\cxx\src\iris_rtc_engine.cc:104 agora::iris::rtc::IrisRtcEngine::CallApi api_type 3 params {"role":1,"options":null}
[2022-04-17 09:33:35.821] [23440] [debug] C:\workspace\workspace\AD\Agora-Iris\IRIS-SDK\rtc\cxx\src\iris_rtc_engine.cc:114 agora::iris::rtc::IrisRtcEngine::CallApi ret 0 result 
[2022-04-17 09:33:35.831] [23440] [debug] C:\workspace\workspace\AD\Agora-Iris\IRIS-SDK\rtc\cxx\src\iris_rtc_engine.cc:104 agora::iris::rtc::IrisRtcEngine::CallApi api_type 4 params {"token":"006c5f7796355124098abcf4aa5e815e93dIAAzuk23dKr86dEPjn6X0M75DY6vouXTX+UBiHnZILj/+gZa8+gAAAAAEAAjgBf2pLtcYgEAAQCiu1xi","channelId":"testing","info":null,"uid":100000000,"options":null}
[2022-04-17 09:33:35.831] [23440] [error] C:\workspace\workspace\AD\Agora-Iris\IRIS-SDK\rtc\cxx\src\iris_rtc_engine.cc:116 agora::iris::rtc::IrisRtcEngine::CallApi ret -17 result 
[2022-04-17 09:33:35.832] [23440] [debug] C:\workspace\workspace\AD\Agora-Iris\IRIS-SDK\rtc\cxx\src\iris_rtc_engine.cc:104 agora::iris::rtc::IrisRtcEngine::CallApi api_type 132 params {"code":-17}
[2022-04-17 09:33:35.832] [23440] [debug] C:\workspace\workspace\AD\Agora-Iris\IRIS-SDK\rtc\cxx\src\iris_rtc_engine.cc:114 agora::iris::rtc::IrisRtcEngine::CallApi ret 0 result
