### ISSUE TITLE
enableDeepLearningDenoise throws an exception in iOS simulator.

### ISSUE THREAD

**Issue by aitaro** [AgoraIO/Agora-Flutter-SDK#560]
**Describe the bug**
enableDeepLearningDenoise throws an exception in iOS simulator.
The SDK version I'm using is 4.2.0.

output log.
```
PlatformException(157, , null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
<asynchronous suspension>
#2      VoiceInterface.initRtcEngine (package:uzu/play_impl/interface/voice/agora_impl.dart:69:5)
<asynchronous suspension>
#3      Controller._initVoice (package:uzu/play/views/check/controller.dart:54:16)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#5      Controller.initState (package:uzu/play/views/check/controller.dart:23:5)
<asynchronous suspension>
```

**To Reproduce**
Problem part of my source code.
```
    rtcEngine = await RtcEngine.createWithContext(
        RtcEngineContext('xxx'));

    await rtcEngine!.setDefaultAudioRoutetoSpeakerphone(true);
    await rtcEngine!.enableAudio();
    await rtcEngine!.disableVideo();
    await rtcEngine!.setChannelProfile(ChannelProfile.Communication);
    await rtcEngine!.enableAudioVolumeIndication(300, 3, true);
    // Here!
    await rtcEngine!.enableDeepLearningDenoise(true);
    await rtcEngine!
        .setAudioProfile(AudioProfile.SpeechStandard, AudioScenario.MEETING);
```

**Expected behavior**
Deep Learning Denoise can be set appropriately without exception.

**Smartphone (please complete the following information):**
 - Device: iPhone8 (simulator)
 - OS: iOS15
 - SDK Version: 4.2.0
 
```
$ flutter --version
Flutter 2.8.1 • channel stable • git@github.com:/flutter/flutter.git
Framework • revision 77d935af4d (4 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1
```

**Comment by LichKing-2234** [comment]
enableDeepLearningDenoise not support simulator
