### ISSUE TITLE
[android] package incompatible Android SDK Build-Tools 31

### ISSUE THREAD

**Issue by aoatmon** [AgoraIO/Agora-Flutter-SDK#608]
# step to reproduce 

1. check that the repo code works without [agora_rtc_engine](https://pub.dev/packages/agora_rtc_engine)

- clone this [repo](https://github.com/aoatmon/agora_bug)
- run `flutter run`
- all works fine

2. change branch and observe the error

- run `git checkout add-agora`
- (optional) delete your `Android/sdk/build-tools/` folder
- [add agora to pubspec](https://github.com/aoatmon/agora_bug/commit/07e8b599aeaaf0682ec464ae8e71dad67aaad20e)
- run `flutter clean`
- run `flutter run`

<details>
  <summary>logs</summary>

```
[+1411 ms] Checking the license for package Android SDK Build-Tools 31 in /Users/francesco/Library/Android/sdk/licenses
[        ] License for package Android SDK Build-Tools 31 accepted.
[        ] Preparing "Install Android SDK Build-Tools 31 (revision: 31.0.0)".
[+17494 ms] "Install Android SDK Build-Tools 31 (revision: 31.0.0)" ready.
[        ] Installing Android SDK Build-Tools 31 in /Users/francesco/Library/Android/sdk/build-tools/31.0.0
[        ] "Install Android SDK Build-Tools 31 (revision: 31.0.0)" complete.
[        ] "Install Android SDK Build-Tools 31 (revision: 31.0.0)" finished.
[  +60 ms] Build-tool 31.0.0 is missing DX at /Users/francesco/Library/Android/sdk/build-tools/31.0.0/dx
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Could not determine the dependencies of task ':agora_rtc_engine:compileDebugAidl'.
[        ] > Installed Build Tools revision 31.0.0 is corrupted. Remove and install again using the SDK Manager.
[        ] * Try:
[        ] > Run with --stacktrace option to get the stack trace.
[        ] > Run with --info or --debug option to get more log output.
[        ] > Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 18s
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[        ] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[        ] See https://docs.gradle.org/7.3.1/userguide/command_line_interface.html#sec:command_line_warnings
[ +369 ms] Running Gradle task 'assembleDebug'... (completed in 19.6s)
[   +3 ms] Exception: Gradle task assembleDebug failed with exit code 1
[        ] "flutter run" took 24,106ms.
[   +4 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:687:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[ +191 ms] ensureAnalyticsSent: 189ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

</details>

<details>
  <summary>doctor</summary>

```
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2.1 21D62 darwin-x64, locale en-EE)
    • Flutter version 2.10.2 at /Users/francesco/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (9 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/francesco/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos      • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 98.0.4758.109

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by aoatmon** [comment]
> Hello @aoatmon , make sure the build tools 31.0.0 is installed correctly on your computer.
> 
> You can follow the tips printed by Gradle, and try again.
> 
> > * What went wrong:
> >   [        ] Could not determine the dependencies of task ':agora_rtc_engine:compileDebugAidl'.
> >   [        ] > Installed Build Tools revision 31.0.0 is corrupted. Remove and install again using the SDK Manager.

hello @littleGnAl 
please look at the logs

```
[+1411 ms] Checking the license for package Android SDK Build-Tools 31 in /Users/francesco/Library/Android/sdk/licenses
[        ] License for package Android SDK Build-Tools 31 accepted.
[        ] Preparing "Install Android SDK Build-Tools 31 (revision: 31.0.0)".
[+17494 ms] "Install Android SDK Build-Tools 31 (revision: 31.0.0)" ready.
[        ] Installing Android SDK Build-Tools 31 in /Users/francesco/Library/Android/sdk/build-tools/31.0.0
[        ] "Install Android SDK Build-Tools 31 (revision: 31.0.0)" complete.
[        ] "Install Android SDK Build-Tools 31 (revision: 31.0.0)" finished.
```

also this optional step is exactly to ensure that the build tools are as "fresh as possible"
> - (optional) delete your `Android/sdk/build-tools/` folder

lastly works perfectly without [agora_rtc_engine](https://pub.dev/packages/agora_rtc_engine), see `step 1)`


do you experience the same issue if you follow the steps provided?

**Comment by aoatmon** [comment]
@littleGnAl 
my mentor found the [fix](https://stackoverflow.com/a/68430992/16087862) it's android's fault

**Comment by kpopovskikh** [comment]
Why was it working fine before then? It's kinda strange that this issue occured only when agora 5.0.0 came out

**Comment by aoatmon** [comment]
@kpopovskikh idk 
@littleGnAl feel free to reopen the issue if needed, but I cannot promise I'll follow up timely

**Comment by sayhellotogithub** [comment]
please remove   buildToolsVersion safeExtGet('buildToolsVersion', '31.0.0')
<img width="578" alt="896FA7BD-4445-450F-B647-C22AB87D8DDF" src="https://user-images.githubusercontent.com/9547097/163512713-cb4f24f4-a7a6-4d81-a64f-30b14dc52811.png">
