### ISSUE TITLE
[FLUTTER WEB] - MissingPluginException(No implementation found for method requestPermissions on channel flutter.baseflow.com/permissions/methods)

### ISSUE THREAD

**Issue by iaohtdev** [AgoraIO/Agora-Flutter-SDK#684]
i can't run flutter web 

Verison :  agora_rtc_engine: ^5.1.1

Please help me, Thanks
Error : 
![image](https://user-images.githubusercontent.com/95197224/168743459-b0712c90-a45e-4a2e-b3ed-591eea7477cb.png)

Error: MissingPluginException(No implementation found for method requestPermissions on channel flutter.baseflow.com/permissions/methods)
    at Object.throw_ [as throw] (http://localhost:54054/dart_sdk.js:5067:11)
at MethodChannel._invokeMethod (http://localhost:54054/packages/flutter/src/services/restoration.dart.lib.js:1560:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:54054/dart_sdk.js:40571:33
    at _RootZone.runUnary (http://localhost:54054/dart_sdk.js:40441:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:54054/dart_sdk.js:35363:29)
    at handleValueCallback (http://localhost:54054/dart_sdk.js:35931:49)
    at Function._propagateToListeners (http://localhost:54054/dart_sdk.js:35969:17)
    at _Future.new.[_completeWithValue] (http://localhost:54054/dart_sdk.js:35817:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:54054/dart_sdk.js:35838:35)
    at Object._microtaskLoop (http://localhost:54054/dart_sdk.js:40708:13)
    at _startMicrotaskLoop (http://localhost:54054/dart_sdk.js:40714:13)
    at http://localhost:54054/dart_sdk.js:36191:9

**Comment by littleGnAl** [comment]
@iaohtdev Can you provide some code for your case?

**Comment by lqmminh** [comment]
this is from other package, permission_handler not support web

**Comment by littleGnAl** [comment]
@lqmminh Thanks, good catch.
