### ISSUE TITLE
Expected a value of type 'int', but got one of type 'String'  Flutter web

### ISSUE THREAD

**Issue by duncanokeyo** [AgoraIO/Agora-Flutter-SDK#730]
**Describe the bug**
Got Expected a value of type 'int', but got one of type 'String'  on flutter web when i  joinChannelWithUserAccount (agora_rtc_engine 5.3.0)
**To Reproduce**
1. join channel using joinChannelWithUserAccount
2. 
**Expected behavior**
I should  be able to join channel with user account

Error: Expected a value of type 'int', but got one of type 'String'
    at Object.throw_ [as throw] (http://localhost:34233/dart_sdk.js:5405:11)
    at Object.castError (http://localhost:34233/dart_sdk.js:5362:15)
    at Object.cast [as as] (http://localhost:34233/dart_sdk.js:5686:17)
    at int.as (http://localhost:34233/dart_sdk.js:20606:19)
    at Object.RtcEngineEventHandlerExt$124process [as RtcEngineEventHandlerExt|process] (http://localhost:34233/packages/agora_rtc_engine/src/impl/rtc_engine_event_handler_impl.dart.lib.js:68:82)
    at http://localhost:34233/packages/agora_rtc_engine/src/rtc_engine_extension_web.dart.lib.js:2274:145
    at _RootZone.runUnaryGuarded (http://localhost:34233/dart_sdk.js:42845:11)
    at [_sendData] (http://localhost:34233/dart_sdk.js:35964:22)
    at _DelayedData.new.perform (http://localhost:34233/dart_sdk.js:39604:28)
    at _StreamImplEvents.new.handleNext (http://localhost:34233/dart_sdk.js:39722:15)
    at async._AsyncCallbackEntry.new.callback (http://localhost:34233/dart_sdk.js:39458:16)
    at Object._microtaskLoop (http://localhost:34233/dart_sdk.js:43223:13)
    at _startMicrotaskLoop (http://localhost:34233/dart_sdk.js:43229:13)
    at http://localhost:34233/dart_sdk.js:38359:9

**Comment by littleGnAl** [comment]
It's a known bug of `joinChannelWithUserAccount` on `agora_rtc_engine` web, you can use `joinChannel` for a temporary workaround at this time.
